name: 'nyc_taxi'
version: '1.0.0'
config-version: 2
profile: 'nyc_taxi'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

vars:
  partition_by: "DATE(tpep_pickup_datetime)"
  cluster_by: "PULocationID"
