version: 2

models:
  - name: stg_trips
    description: "Datos limpios de viajes"
    config:
      materialized: table
      partition_by: "DATE(tpep_pickup_datetime)"
      cluster_by: "PULocationID"
    
    columns:
      - name: tpep_pickup_datetime
        tests:
          - not_null
      - name: PULocationID
        tests:
          - not_null
          - relationships:
              to: ref('taxi_zones')
              field: LocationID
